spin_manifest_version = 2

[application]
name = "hellocompose"
version = "0.1.0"
authors = ["Radu Matei <radu.matei@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "hellocompose"

[component.hellocompose]
# source = "target/wasm32-wasi/release/hellocompose.wasm"
source = "composed.wasm"
allowed_outbound_hosts = []
[component.hellocompose.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
